databases:
  - name: alxtraveldb
    plan: free
    databaseName: alx_travel_db
    user: alx_travel_db

services:
  - type: web
    plan: free
    name: alx-travel-app
    runtime: python
    buildCommand: './alx_travel_app/build.sh'
    startCommand: 'python -m gunicorn alx_travel_app.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alxtraveldb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4