databases:
  - name: alxtraveldb
    plan: free
    databaseName: alx_travel_db
    user: alx_travel_db

services:
  - type: web
    plan: free
    name: alx-travel-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn alx_travel_app.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alxtraveldb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: CELERY_BROKER_URL
        value: amqp://guest:guest@rabbitmq:5672//

  - type: pserv
    name: rabbitmq
    plan: free
    runtime: docker
    image:
      url: rabbitmq:3-management
    envVars:
      - key: RABBITMQ_DEFAULT_USER
        value: guest
      - key: RABBITMQ_DEFAULT_PASS
        value: guest

  - type: worker
    name: celery-worker
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: >
      bash -c "until nc -z rabbitmq 5672; do echo 'Waiting for RabbitMQ...'; sleep 3; done;
      celery -A alx_travel_app worker --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alxtraveldb
          property: connectionString
      - key: CELERY_BROKER_URL
        value: amqp://guest:guest@rabbitmq:5672//

  - type: worker
    name: celery-beat
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: >
      bash -c "until nc -z rabbitmq 5672; do echo 'Waiting for RabbitMQ...'; sleep 3; done;
      celery -A alx_travel_app beat --loglevel=INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alxtraveldb
          property: connectionString
      - key: CELERY_BROKER_URL
        value: amqp://guest:guest@rabbitmq:5672//
